[book]
authors = ["bingryan"]
language = "cn"
multilingual = false
src = "src"
title = "Prompt Engineering for Developers"

[output.html]
additional-css = ["theme/css/custom.css"]
additional-js = ["theme/js/custom.js"]
git-repository-url = "https://github.com/bingryan/Prompt-Engineering-for-Developers"
edit-url-template = "https://github.com/bingryan/Prompt-Engineering-for-Developers/edit/main/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2


[output.html.fold]
enable = true
level = 0

[rust]
edition = "2021"